<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "yacy"
 *
 * Auto generated by Extension Builder 2014-10-26
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Yacy Search',
    'description' => 'Add a yacy search to you website.',
    'category' => 'plugin',
    'author' => 'Eike Starkmann',
    'author_email' => 'eikestarkmann@posteo.de',
    'state' => 'stable',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '4.0.2',
    'constraints' => [
        'depends' => [
            'typo3' => '9.0.0-10.4.99',
        ],
        'conflicts' => [
        ],
        'suggests' => [
        ],
    ],
];
