<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "yacy"
 *
 * Auto generated by Extension Builder 2014-10-26
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Yacy Search',
	'description' => 'Add a yacy search to you website.',
	'category' => 'plugin',
	'author' => 'Eike Starkmann',
	'author_email' => 'eikestarkmann@posteo.de',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '3.0.0',
	'constraints' => array(
		'depends' => array(
			'typo3' => '8.7.0 - 8.7.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);
